server:
  port: 1111
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eurovisiondb
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
